@startuml
!theme cerulean
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

top to bottom direction

Person(user, "Пользователь", "Пользователь умного дома")

System(smartHouseSystem, "система Умный Дом", "Приложение-монолит")
System_Ext(tApi, "Temperature API", "Внешняя система получения температуры")
System_Ext(hApi, "Датчики температуры", "Физические устройства в домах")

Rel(user, smartHouseSystem, "Управление устройствами")
Rel(smartHouseSystem, tApi, "Получение температуры")
Rel(smartHouseSystem, hApi, "Управление устройствами")

@enduml