@startuml
!theme cerulean
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Container(ui, "UI", "JavaScript, Vue.js", "Веб-приложение для обращения к API")
Container(mobile, "Mobile App", "iOS, Andriod", "Мобильное приложение для обращения к API")

System_Boundary(c0, "") {

  System_Boundary(c1, "Компоненты backend-приложения") {
    Container(apiController, "API Controller", "Python, Flask", "API-эндпоинты для управления устройствами")
    Container(deviceService, "Device Service", "Python, Flask", "Бизнес-логика управления устройствами")
    Container(deviceClient, "Device Client", "Python", "Отправляет команды на устройство")
    Container(bus, "Bus Service", "Python", "Работает с шиной данных")
    Container(deviceRepository, "Device Repository", "Python, SQLAlchemy", "Слой для работы с базой данных")
  }
  
  ContainerDb(database, "Database", "PostgreSQL", "Хранение данных устройств и состояний")
  ContainerQueue(eventBus, "Event Bus", "RabbitMQ", "Обмен событиями (device.online, gate.opened)")
}

System_Ext(device, "Устройство", "Физические устройства в домах")

Rel(ui, apiController, "Вызывает API", "HTTPS")
Rel(mobile, apiController, "Вызывает API", "HTTPS")

Rel(apiController, deviceService, "Обрабатывает команды ")

Rel_D(deviceService, bus, "Получение информации об устройствах, Отправка телеметрии")
Rel(deviceService, deviceRepository, "SQL")
Rel(deviceService, deviceClient, "Управление устройством")
Rel_L(deviceClient, device, "Отправка команд на устройство")

Rel(bus, eventBus, "Отправка \ получение команд в реестр устройств")
Rel_D(deviceRepository, database, "Пишет и читает в хранилище")


@enduml