@startuml
!theme cerulean
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Container(ui, "UI", "JavaScript, Vue.js", "Веб-приложение для обращения к API")
Container(mobile, "Mobile App", "iOS, Andriod", "Мобильное приложение для обращения к API")

System_Boundary(c0, "") {

  System_Boundary(c1, "Компоненты backend-приложения") {
    Container(deviceController, "Device Controller", "Python, Flask", "API-эндпоинты для управления устройствами")
    Container(deviceService, "Device Service", "Python, Flask", "Бизнес-логика управления устройствами")
    Container(authService, "Auth Service", "Python, Flask", "Валидация JWT-токена")
    Container(bus, "Bus Service", "Python", "Работает с шиной данных")
    Container(deviceRepository, "Device Repository", "Python, SQLAlchemy", "Слой для работы с базой данных")
  }
  
  ContainerDb(database, "Database", "PostgreSQL", "Хранение данных устройств и состояний")
  ContainerQueue(eventBus, "Event Bus", "RabbitMQ", "Обмен событиями (device.online, gate.opened)")
}


Rel(ui, deviceController, "Вызывает API, передает JWT-токен", "HTTPS")
Rel(mobile, deviceController, "Вызывает API, передает JWT-токен", "HTTPS")
Rel(deviceController, authService, "Валидация JWT-токена и получения пользователя")
Rel(deviceController, deviceService, "Запрашивает данные или инициирует изменения")

Rel_D(deviceService, bus, "Отправка уведомлений о добавлении\изменнии оборудования")

Rel(bus, eventBus, "Отправка \ получение команд")

Rel(deviceService, deviceRepository, "SQL")

Rel_D(deviceRepository, database, "Пишет и читает в хранилище")
@enduml