@startuml
!theme cerulean
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Container(ui, "UI", "JavaScript, Vue.js", "Веб-приложение для обращения к API")
Container(mobile, "Mobile App", "iOS, Andriod", "Мобильное приложение для обращения к API")

System_Boundary(c0, "") {

  System_Boundary(c1, "Компоненты backend-приложения") {
    Container(metricsController, "Metrics Controller", "Python, Flask", "API-эндпоинты для получения метрик")
    Container(metricsSevice, "Metrics Service", "Python, Flask", "Бизнес-логика получения метрик")
    Container(authService, "Auth Service", "Python, Flask", "Валидация JWT-токена")
    Container(bus, "Bus Service", "Python", "Работает с шиной данных")
    Container(metricsRepository, "Metrics Repository", "Python, SQLAlchemy", "Слой для работы с базой данных")
  }
  
  ContainerDb(database, "Database", "PostgreSQL", "Хранение данных устройств и состояний")
  ContainerQueue(eventBus, "Event Bus", "RabbitMQ", "Обмен событиями (telemetry)")
}


Rel(ui, metricsController, "Вызывает API, передает JWT-токен", "HTTPS")
Rel(mobile, metricsController, "Вызывает API, передает JWT-токен", "HTTPS")

Rel(metricsController, authService, "Валидация JWT-токена, получение пользователя")
Rel(metricsController, metricsSevice, "Запрашивает данные")

Rel_U(bus, metricsSevice, "Получение и обработка данных телеметрии")
Rel(bus, eventBus, "Отправка \ получение команд")

Rel(metricsSevice, metricsRepository, "SQL")
Rel_D(metricsRepository, database, "Пишет и читает в хранилище")

@enduml