version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: smarthome-db
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - smarthome-network

  rabbitmq:
    image: rabbitmq:3.10.8-alpine
    container_name: smarthome-rabbitmq
    ports:
      - "${RABBITMQ_PORT_AMQP:-5672}:5672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-guest}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - smarthome-network

  telemetry:
    build:
      context: ./telemetry
      dockerfile: Dockerfile
    container_name: telemetry-app
    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_started
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/smarthome
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - RABBITMQ_QUEUE=telemetry
    ports:
      - "8081:8081"
    restart: unless-stopped
    networks:
      - smarthome-network

  heating:
    build:
      context: ./heating
      dockerfile: Dockerfile
    container_name: heating-app
    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_started
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/smarthome
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - RABBITMQ_TELEMETRY_QUEUE=telemetry
      - PORT=8082
    ports:
      - "8082:8082"
    restart: unless-stopped
    networks:
      - smarthome-network

  gates:
    build:
      context: ./gates
      dockerfile: Dockerfile
    container_name: gates-app
    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_started
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/smarthome
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - RABBITMQ_TELEMETRY_QUEUE=telemetry
      - PORT=8083
    ports:
      - "8083:8083"
    restart: unless-stopped
    networks:
      - smarthome-network

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  smarthome-network:
    driver: bridge